Update .config/bin/git-extras/git-sync-this-repo

diff --git a/private_dot_config/bin/git-extras/executable_git-sync-this-repo b/private_dot_config/bin/git-extras/executable_git-sync-this-repo
--- a/private_dot_config/bin/git-extras/executable_git-sync-this-repo
+++ b/private_dot_config/bin/git-extras/executable_git-sync-this-repo
@@ -1,36 +1,46 @@
-#!/usr/bin/env bash
+#!/usr/bin/env zsh
+export GIT_OPTIONAL_LOCKS=0      # prevent unnecessary lock files
+cd "$(dirname "$0")" || return 1 # go to location of this script, i.e., the git root
+#───────────────────────────────────────────────────────────────────────────────
 
-# this is a modified version of chrisgeiger's script without any dependencies and works on linux
+# if no changes, just pull & push
+change_count=$(git status --porcelain | wc -l | tr -d " ")
 
-
-export GIT_OPTIONAL_LOCKS=0    # prevent unnecessary lock files
-pwd
-if [[ ! -d .git ]]; then
-	echo "Not a git repository"
-	exit 1
+if [[ $change_count -eq 0 ]]; then
+	git pull --no-progress && git push --no-progress
+	return $?
 fi
 
 #───────────────────────────────────────────────────────────────────────────────
 
-files_changed="$(git status --porcelain | wc -l | tr -d ' ')"
-device_name=$(uname -n)
-device_type=$(hostnamectl | grep -E "Chassis" | awk -F ":" '{print $2}')
-full_device_info="$device_name $device_type"
-commit_msg="$full_device_info ($files_changed)"
+# determine commit message
+changed_files="$(git status --porcelain | cut -c4- |
+	sed -Ee 's/^"|"$//g' -Ee 's|^|./|' -Ee 's|/$||')"
+common=$(echo "$changed_files" | head -n1) # initialize
 
-if [[ $files_changed -gt 0 ]]; then
-	git add --all &&
-		git commit -m "$commit_msg" --author="🤖 automated<cron@job>" --no-verify ||
-		exit 1
+while read -r filepath; do # don't call it `path`, messes with `$PATH`
+	while [[ ! "$filepath" =~ ^$common ]]; do
+		common=$(dirname "$common")
+	done
+done < <(echo "$changed_files")
+[[ -d "$common" ]] && common="$common/" # distinguish from files with trailing `/`
+common=$(echo "$common" | cut -c3-)     # remove leading `./`
+while [[ ${#common} -gt 60 ]]; do
+	common=${common#*/}                                                       # remove first directory
+	[[ "$common" != *"/"* && ${#common} -gt 60 ]] && common="${common:0:59}…" # shorten files with long names
+done
+
+device_name=$(scutil --get ComputerName | cut -d" " -f3-)
+if [[ -z "$common" ]]; then
+	commit_msg="$device_name ($change_count files)"
+else
+	commit_msg="$device_name ($common)"
 fi
 
-# loop git add-commit-pull-push, since when between add and push files have been
-# changed, the push will fail
-i=0
-while true; do
-	sleep 0.5 # prevent "Cannot rebase on multiple branches"
-	git pull && git push && exit 0
-	sleep 1
-	i=$((i + 1))
-	[[ $i -gt 3 ]] && exit 1
-done
+#───────────────────────────────────────────────────────────────────────────────
+
+# add-commit-pull-push
+git add --all
+git commit --message="$commit_msg" --author="🤖 automated<cron@job>" || return 1 # fail with pre-commit check
+git pull --no-progress && git push --no-progress
+return $?
